name: coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cover:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2