name: unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          go get ./...

      - name: Run tests
        run: |
          go clean -testcache; go test ./... -coverprofile=./cover.out

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          threshold-total: 80
          badge-file-name: coverage.svg
