name: unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Tests and coverage on client
        run: |
          go clean -testcache; go test client/... -coverprofile=cover.out.tmp
          cat cover.out.tmp | grep -v 'tui'  > cover.out
          go tool cover -func=cover.out | grep total

      - name: Tests on server
        run: |
          go clean -testcache; go test server/... -coverprofile=cover.out
          go tool cover -func=cover.out | grep total
