name: unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          go get ./...

      - name: Tests on client
        run: |
          go clean -testcache; go test client/...          

      - name: Tests on server
        run: |
          go clean -testcache; go test server/...          
